exam/urls.py
from django.urls import path
from . import views

app_name = 'exam'
urlpatterns = [
    path('', views.IndexView.as_view(),name="index"),
    path('subject/<str:category>/', views.SubjectView.as_view(),name='subject'),
    path('subject2/<str:category>', views.Subject2View.as_view(),name='subject2'),
    path('video/<int:pk>',views.VideoView.as_view(),name='video'),
    path('inquiry/', views.InquiryView.as_view(),name="inquiry"),
    path('exam-list/', views.ExamListView.as_view(), name='exam_list'),
    path('exam-detail/<int:pk>/', views.ExamDetailView.as_view(), name='exam_detail'),
    path('exam-create/', views.ExamCreateView.as_view(), name='exam_create'),
    path('exam-update/<int:pk>', views.ExamUpdateView.as_view(), name='exam_update'),
    path('exam-delete/<int:pk>', views.ExamDeleteView.as_view(), name='exam_delete'),
    path('video/<int:pk>/like/', views.like, name='like'),
    path('video/<int:pk>/startcount/',views.startcount, name='startcount'),
    path('subject2/<str:category>/<str:select>/',views.select, name='select'),
    path('mypage/', views.MypageView.as_view(), name="mypage"),
    path('mychannel/<int:pk>/', views.MychannelView.as_view(), name="mychannel"),
    path('blog/<int:pk>/',views.BlogView.as_view(), name='blog'),
    path('file/<int:pk>/',views.FileView.as_view(), name='file'),
    path('list/<int:pk>/', views.listfunc, name='list'),
    path('question/<int:pk>/', views.QuestionView.as_view(), name='question'),
    path('mypage-question/', views.MypageQuestionView.as_view(), name="mypage_question"),
    path('course/<int:pk>', views.CourseView.as_view(), name="course"),
]

exam_study/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path,include
from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('exam.urls')),
]

#開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

exam/models.py
from accounts.models import CustomUser
from django.db import models
from taggit.managers import TaggableManager


# Create your models here.
class Category(models.Model):
    name = models.CharField('カテゴリー', max_length=50)
    slug = models.CharField('スラッグ', max_length=50, blank=True, null=True)

    def __str__(self):
        return self.name

class SubCategory(models.Model):
    name = models.CharField('カテゴリー', max_length=50)

    def __str__(self):
        return self.name

class Course(models.Model):
    name = models.CharField('コース名', max_length=50)


    def __str__(self):
        return self.name

class SubCourse(models.Model):
    name = models.CharField('サブコース名', max_length=50)
    course =models.ForeignKey(Course, verbose_name='コース', on_delete=models.PROTECT, blank=True, null=True)

    def __str__(self):
        return self.name


class Channel(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    name = models.CharField(verbose_name='チャンネル名', max_length=40)
    abstract = models.TextField(verbose_name='説明文', blank=True, null=True)
    photo1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)


    def __str__(self):
        return self.name


class Exam(models.Model):
    """動画モデル"""
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    content = models.TextField(verbose_name='本文', blank=True, null=True)
    photo1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    document = models.FileField(verbose_name='動画1', upload_to='documents/', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)
    tags = TaggableManager(blank=True)
    good = models.IntegerField(default=0)
    start_count = models.PositiveIntegerField(default=0)
    views = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, verbose_name='カテゴリー',on_delete=models.PROTECT,blank=True, null=True)
    subcategory = models.ManyToManyField(SubCategory, verbose_name='サブカテゴリー', blank=True, null=True)
    channel = models.ForeignKey(Channel, verbose_name='チャンネル名', on_delete=models.PROTECT, blank=True, null=True)
    url = models.URLField(verbose_name='リンクURL', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Exam'

        def __str__(self):
            return self.title

class Blog(models.Model):
    """ブログモデル"""
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    content = models.TextField(verbose_name='本文', blank=True, null=True)
    photo1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)
    tags = TaggableManager(blank=True)
    good = models.IntegerField(default=0)
    start_count = models.PositiveIntegerField(default=0)
    views = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, verbose_name='カテゴリー',on_delete=models.PROTECT,blank=True, null=True)
    subcategory = models.ManyToManyField(SubCategory, verbose_name='サブカテゴリー', blank=True, null=True)
    channel = models.ForeignKey(Channel, verbose_name='チャンネル名', on_delete=models.PROTECT, blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Blog'

        def __str__(self):
            return self.title

class File(models.Model):
    """ファイルモデル"""
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    comment = models.TextField(verbose_name='コメント', blank=True, null=True)
    file = models.FileField(verbose_name='ファイル', blank=True, null=True)
    photo1 = models.ImageField(verbose_name='サムネ画像', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)
    tags = TaggableManager(blank=True)
    good = models.IntegerField(default=0)
    start_count = models.PositiveIntegerField(default=0)
    views = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, verbose_name='カテゴリー',on_delete=models.PROTECT,blank=True, null=True)
    subcategory = models.ManyToManyField(SubCategory, verbose_name='サブカテゴリー', blank=True, null=True)
    channel = models.ForeignKey(Channel, verbose_name='チャンネル名', on_delete=models.PROTECT, blank=True, null=True)

    class Meta:
        verbose_name_plural = 'File'

        def __str__(self):
            return self.title

class Comment(models.Model):
    """コメントモデル"""
    user =models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    content = models.ForeignKey(Exam, verbose_name='コンテンツ', on_delete=models.PROTECT)
    comment = models.TextField(verbose_name='コメント', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Comment'

class Register(models.Model):
    """チャンネル登録モデル"""
    user = models.ForeignKey(CustomUser, verbose_name='登録者', on_delete=models.PROTECT)
    channel = models.ForeignKey(Channel, verbose_name='登録チャンネル', on_delete=models.PROTECT)

class CourseRegister(models.Model):
    """コース登録モデル"""
    user = models.ForeignKey(CustomUser, verbose_name='コース登録者', on_delete=models.PROTECT)
    course = models.ForeignKey(Course, verbose_name='登録コース', on_delete=models.PROTECT)

class Favorite(models.Model):
    """お気に入りモデル"""
    user = models.ForeignKey(CustomUser, verbose_name='お気に入り登録者', on_delete=models.PROTECT)
    video = models.ForeignKey(Exam, verbose_name='登録動画', on_delete=models.PROTECT)

class Question(models.Model):
    """問題モデル"""
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    comment = models.TextField(verbose_name='コメント', blank=True, null=True)
    question = models.FileField(verbose_name='問題', blank=True, null=True)
    photo1 = models.ImageField(verbose_name='サムネ画像', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)
    tags = TaggableManager(blank=True)
    good = models.IntegerField(default=0)
    start_count = models.PositiveIntegerField(default=0)
    views = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, verbose_name='カテゴリー',on_delete=models.PROTECT,blank=True, null=True)
    subcategory = models.ManyToManyField(SubCategory, verbose_name='サブカテゴリー', blank=True, null=True)
    channel = models.ForeignKey(Channel, verbose_name='チャンネル名', on_delete=models.PROTECT, blank=True, null=True)
    course = models.ForeignKey(Course, verbose_name='コース名',on_delete=models.PROTECT,blank=True, null=True)
    subcourse = models.ForeignKey(SubCourse, verbose_name='サブコース名',on_delete=models.PROTECT,blank=True, null=True)
    difficult = models.IntegerField(verbose_name='難易度', default=0)
    important = models.IntegerField(verbose_name='重要度', default=0)
    time = models.IntegerField(verbose_name='目標解答時間', default=0)


    class Meta:
        verbose_name_plural = 'Question'

        def __str__(self):
            return self.title

class UserAnswer(models.Model):
    """解答状況モデル"""
    user = models.ForeignKey(CustomUser, verbose_name='解答ユーザー', on_delete=models.PROTECT)
    answer = models.ForeignKey(Question, verbose_name='解答問題', on_delete=models.PROTECT)
    collect = models.IntegerField(verbose_name='正誤', blank=True, null=True)
    memo = models.TextField(verbose_name='メモ', blank=True, null=True)
    photo = models.ImageField(verbose_name='解答画像', blank=True, null=True)
    point = models.IntegerField(verbose_name='点数', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    time = models.IntegerField(verbose_name='答時間', default=0)

exam/forms.py
from django import forms
from django.core.mail import EmailMessage
from .models import Exam

class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control col-11'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ{}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = 'admin@example.com'
        to_list = [
            'test@example.com'
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

class ExamCreateForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = ('title', 'content', 'photo1', 'document')

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

exam/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
  <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">

  <!--My style -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
  {% block head %}{% endblock %}

</head>

<body>

<div id="wrapper">
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'exam:index' %}">Exam</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% block active_inquiry %}{% endblock %}">
            <a class="nav-link" href="{% url 'exam:inquiry' %}">お問い合わせ</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item {% block active_exam_list %}{% endblock %}">
            <a class="nav-link" href="{% url 'exam:mypage' %}">MyPage</a>
          </li>
          {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
            </li>
          {% else %}
            <li class="nav-item {% block active_signup %}{% endblock %}">
              <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
            </li>
            <li class="nav-item {% block active_login %}{% endblock %}">
              <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% block header %}{% endblock %}

  {% if messages %}
  <div class="container">
    <div class="row">
      <div class="my-div-style w-100">
        <ul class="messages" style="list-style: none;">
          {% for message in messages %}
          <li {% if message.tags %} class="{{message.tags}}" {% endif %}>
            {{message}}
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  {% endif %}

  {% block contents %}{% endblock %}

  <!-- Footer -->
  <footer class="py-5 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white small">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/p5@0.10.2/lib/p5.js"></script>
  <script src="{% static 'javascript/custom.js' %}"></script>

  {% block javascript %}{% endblock %}
</div>
</body>

</html>

exam/templates/blog.html
{% extends 'base.html' %}
{% load static %}

{% block title %}詳細{% endblock %}

{% block active_exam_list %}active{% endblock %}

<!-- Main Content -->

{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
     <div class="row">
      <div class="col-9">
        <div class="row py-2 video-wrap">
          {% if object %}
            <div data-href="{% url 'exam:startcount' object.pk %}" id="startcount" class="img-fluid w-100">
                {% csrf_token %}
                {{object.content | safe}}
                <img src="{{object.photo1.url}}" />
                <iframe src="{% static 'pdf/2020_math1a.pdf' %}"></iframe>
            </div>
          {% endif %}
        </div>


      </div>


      <div class="col-3">

      </div>

     </div>

      <a class="btn btn-success mt-5 mb-3" href="{% url 'exam:exam_update' object.pk %}">編集</a>
      <a class="btn btn-success mt-5 ml-2 mb-3" href="{% url 'exam:exam_delete' object.pk %}">削除</a>

    </div>
</div>
{% endblock %}

exam/templates/mypage.html
{% extends 'base.html' %}

{% load static %}

{% block title %}MyPage{% endblock %}

<!--メインビジュアル-->
{% block header %}
<!--パンくずリスト-->
<div class="pt-5 mt-3">
<nav aria-label="breadcrumb">
    <ol class="breadcrumb container">
        <li class="breadcrumb-item">
            <a href="{% url 'exam:index' %}">Home</a>
        </li>

        <li class="breadcrumb-item active" aria-current="page">
            math1
        </li>
    </ol>
</nav>
</div>
<!--/パンくずリスト-->
{% endblock %}
<!--/メインビジュアル-->


{% block contents %}
<!--コンテンツ1-->
<section class="bg-light py-4">
    <div class="container bg-white">
      <div class="row align-items-center py-4">
        <div class="col-12 border-bottom">
            <div class="card-body d-flex justify-content-start">
                <img src="{{user.picture.url}}" class="rounded-circle" width="90" height="90"/>
                <div class="ml-3">
                    <h2>ようこそ{{user}}さん！</h2>
                </div>
            </div>
        </div>
      </div>
    </div>
</section>
<!--/コンテンツ1-->

<!--コンテンツ2-->
<section class="bg-light py-4">
    <div class="container bg-white">
      <div class="row align-items-center py-4">
        <div class="col-12 border-bottom">
            <h4>登録チャンネル</h4>
        </div>
      </div>

      <div class="row">
          {% for register in registerchannel_list %}
          <div class="col-md-6">
              <div class="card mb-3">
                  <div class="card-body d-flex justify-content-start">
                      <img src="{{register.channel.photo1.url}}" class="rounded-circle" width="100" height="100"/>
                      <div class="ml-3">
                        <p>{{register.channel.name}}</p>
                        <p>登録者数４人</p>
                        <button type="button" class="btn btn-secondary">チャンネル登録</button>
                        <a href="{% url 'exam:mychannel' register.channel.pk %}">クアラルンプール</a>
                      </div>
                  </div>
              </div>
          </div>
          {% endfor %}
      </div>

    </div>
</section>
<!--/コンテンツ2-->

<!--コンテンツ3-->
<section class="bg-light py-4">
    <div class="container bg-white">
      <div class="row align-items-center py-4">
        <div class="col-12 border-bottom">
            <h4>お気に入り一覧</h4>
        </div>
      </div>

      <div class="row">
          {% for favorite in favorite_list %}
          <div class="col-md-4">
              <div class="card mb-3">
                  <img src="{{favorite.video.photo1.url}}" class="img-fluid"/>
                  <div class="card-body d-flex justify-content-start">
                      <img src="{{favorite.video.channel.photo1.url}}" class="rounded-circle" width="50" height="50"/>
                      <div class="ml-3">
                        <h4 class="card-title">{{favorite.video.title}}</h4>
                        <p>{{favorite.video.channel.name}}・{{favorite.video.created_at}}</p>
                        <a href="{% url 'exam:video' favorite.video.pk %}">クアラルンプール</a>
                      </div>
                  </div>
              </div>
          </div>
          {% endfor %}
      </div>

      <div class="row align-items-center py-4">
        <div class="col-12 border-bottom">
            <h4>おすすめ</h4>
        </div>
      </div>

      <div class="row">
          <div class="col-md-4">
              <div class="card mb-3">
                  <video src="{% static 'documents/動画1.mp4' %}" poster="/media/N国立花.jpg" class="img-fluid" controls></video>
                  <div class="card-body d-flex justify-content-between">
                      <h4 class="card-title">動画1</h4>
                      <button type="button" class="btn btn-secondary">詳しく見る</button>
                  </div>
              </div>
          </div>

          <div class="col-md-4">
              <div class="card mb-3">
                  <video src="{% static 'documents/動画1.mp4' %}" poster="/media/N国立花.jpg" class="img-fluid" controls></video>
                  <div class="card-body d-flex justify-content-between">
                      <h4 class="card-title">動画2</h4>
                      <button type="button" class="btn btn-secondary">詳しく見る</button>
                  </div>
              </div>
          </div>

          <div class="col-md-4">
              <div class="card mb-3">
                  <video src="{% static 'documents/動画1.mp4' %}" poster="/media/N国立花.jpg" class="img-fluid" controls></video>
                  <div class="card-body d-flex justify-content-between">
                      <h4 class="card-title">動画3</h4>
                      <button type="button" class="btn btn-secondary">詳しく見る</button>
                  </div>
              </div>
          </div>
      </div>

    </div>
</section>
<!--/コンテンツ3-->


{% endblock %}

exam/templates/question.html
{% extends 'base.html' %}
{% load static %}

{% block title %}詳細{% endblock %}

{% block active_exam_list %}active{% endblock %}

<!-- Main Content -->

{% block contents %}
<section class="bg-light">
    <div class="container bg-white">
        <div class="my-div-style w-100">
         <div class="row">
          <div class="col-8">
            <h3>{{object.title}}</h3>
            <div class="row py-2 video-wrap">
              {% if object %}
                <div data-href="{% url 'exam:startcount' object.pk %}" id="startcount" class="embed-responsive embed-responsive-1by1">
                    {% csrf_token %}
                    <iframe src="{{object.question.url}}"></iframe>

                </div>
              {% endif %}
            </div>

            <div class="row py-2">

            </div>


          </div>

          <div class="col-4">
              <div class="row justify-content-around">
                  <div class="col-5 py-2">
                      <h4><button type="button" class="btn btn-primary">難易度</button> {{object.difficult}}</h4>
                  </div>

                  <div class="col-5 py-2">
                      <h4><button type="button" class="btn btn-primary">重要度</button> {{object.important}}</h4>
                  </div>
              </div>

              <div class="row justify-content-around">
                  <div class="col-11 py-2">
                      <h4><button type="button" class="btn btn-primary">目標解答時間</button> {{object.time}}分</h4>
                  </div>
              </div>

              <div class="row justify-content-around">
                  <div class="col-11 py-2">
                      <h4>類題</h4>
                      {% for question in question_list %}
                      <div class="row">
                          <a href="{% url 'exam:question' question.pk %}">{{question.title}}</a>
                      </div>
                      {% endfor %}
                  </div>
              </div>

          </div>

         </div>



        </div>
    </div>
</section>
{% endblock %}

exam/templates/video.html
{% extends 'base.html' %}
{% load static %}

{% block title %}詳細{% endblock %}

{% block active_exam_list %}active{% endblock %}

  <!-- Main Content -->
{% block contents %}
<div class="container-fluid">
    <div class="my-div-style w-100">
     <div class="row">
      <div class="col-9">
        <div class="row py-2 video-wrap">
          {% if object.document %}
            <div data-href="{% url 'exam:startcount' object.pk %}" id="startcount" class="img-fluid w-100">
                {% csrf_token %}
                <video poster="{{object.photo1.url}}" controls class="img-fluid w-100">
                    <source src="{{object.document.url}}" type="video/mp4" />
                    <img src="{{object.photo1.url}}" />
                </video>
            </div>
          {% endif %}
        </div>

        <div class="row py-4 ">
            <h1>{{object.title}}</h1>
        </div>

        <div class="row py-1 ">
            <div class="col-10">
                総再生回数{{object.start_count}}回・{{object.created_at}}・{{object.views}}閲覧
            </div>
            <div class="col-1">
                <p><a href="{% url 'exam:like' object.pk %}"><i class="fas fa-lg fa-heart"></i>{{object.good}}いいね</a></p>
            </div>
            <div class="col-1">
                <p><a href="{% url 'exam:like' object.pk %}"><i class="fas fa-lg fa-heart"></i>{{object.good}}駄目ね</a></p>
            </div>
        </div>


        <div class="row py-4 ">
            <div class="col-1">
                <img src="{{object.channel.photo1.url}}" class="rounded-circle" width="50" height="50"/>
            </div>
            <div class="col-6">
                <a href="{% url 'exam:mychannel' object.channel.pk %}">
                    <h3 class="text-left">{{object.channel.name}}</h3>
                    <!--<h5>{{object.content}}</h5>-->
                </a>
            </div>

            <div class="col-5 text-right">
                <button type="button" class="btn btn-secondary">チャンネル登録</button>
            </div>
        </div>

        <div class="row py-4 ">
          <div class="col-12">
            <h3>コメント一覧</h3>
            {% for comment in comment_list %}
            <div class="card">
                <div class="card-body d-flex justify-content-start">
                    <img src="{{comment.user.picture.url}}" class="rounded-circle" width="50" height="50"/>
                    <div class="ml-5">
                        <h4 class="card-title">{{ comment.user.username }}・{{ comment.updated_at }}</h4>
                        <h3 class="card-title">{{ comment.comment }}</h3>
                    </div>
                </div>
            </div>
            {% endfor %}
          </div>
        </div>

      </div>


      <div class="col-3">
        {% for relation in tag_list %}
        <div class="card mb-3 w-75 mx-auto">
            <video src="{{ relation.document.url }}" poster="{{relation.user.picture.url}}" class="img-fluid" controls></video>
            <div class="card-body d-flex justify-content-between">
                <h4 class="card-title">{{ relation.title}}</h4>
                <button type="button" class="btn btn-secondary">詳しく見る</button>
            </div>
        </div>
        {% endfor %}
      </div>

     </div>



      <a class="btn btn-success mt-5 mb-3" href="{% url 'exam:exam_update' object.pk %}">編集</a>
      <a class="btn btn-success mt-5 ml-2 mb-3" href="{% url 'exam:exam_delete' object.pk %}">削除</a>

    </div>
</div>
{% endblock %}